# Site settings
title: Evan's Blog
email: evan.alexander.hawk@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ehawk823.gihub.io" # the base hostname & protocol for your site
github_username:  ehawk823

# Build settings
markdown: kramdown
