# Site settings
title: Evan's Blog
email: evan.alexander.hawk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ehawk823.gihub.io" # the base hostname & protocol for your site
twitter_username: evanahawk
github_username:  ehawk823

# Build settings
markdown: kramdown
